"""
Thin re-export of the pybind11 `_core` extension (read_file/write_file plus
the IMREAD_ERR_*/BUFFER_FORMAT_* constants). See ReadIM.extra for the
friendly wrappers.
"""
from __future__ import division, print_function, absolute_import

from . import _core

read_file = _core.read_file
write_file = _core.write_file
get_vector_components = _core.get_vector_components

IMREAD_ERR_NO = _core.IMREAD_ERR_NO
IMREAD_ERR_FILEOPEN = _core.IMREAD_ERR_FILEOPEN
IMREAD_ERR_HEADER = _core.IMREAD_ERR_HEADER
IMREAD_ERR_FORMAT = _core.IMREAD_ERR_FORMAT
IMREAD_ERR_DATA = _core.IMREAD_ERR_DATA
IMREAD_ERR_MEMORY = _core.IMREAD_ERR_MEMORY

BUFFER_FORMAT__NOTUSED = _core.BUFFER_FORMAT__NOTUSED
BUFFER_FORMAT_MEMPACKWORD = _core.BUFFER_FORMAT_MEMPACKWORD
BUFFER_FORMAT_FLOAT = _core.BUFFER_FORMAT_FLOAT
BUFFER_FORMAT_WORD = _core.BUFFER_FORMAT_WORD
BUFFER_FORMAT_DOUBLE = _core.BUFFER_FORMAT_DOUBLE
BUFFER_FORMAT_FLOAT_VALID = _core.BUFFER_FORMAT_FLOAT_VALID
BUFFER_FORMAT_IMAGE = _core.BUFFER_FORMAT_IMAGE
BUFFER_FORMAT_VECTOR_2D_EXTENDED = _core.BUFFER_FORMAT_VECTOR_2D_EXTENDED
BUFFER_FORMAT_VECTOR_2D = _core.BUFFER_FORMAT_VECTOR_2D
BUFFER_FORMAT_VECTOR_2D_EXTENDED_PEAK = _core.BUFFER_FORMAT_VECTOR_2D_EXTENDED_PEAK
BUFFER_FORMAT_VECTOR_3D = _core.BUFFER_FORMAT_VECTOR_3D
BUFFER_FORMAT_VECTOR_3D_EXTENDED_PEAK = _core.BUFFER_FORMAT_VECTOR_3D_EXTENDED_PEAK
BUFFER_FORMAT_RGB_MATRIX = _core.BUFFER_FORMAT_RGB_MATRIX
BUFFER_FORMAT_RGB_32 = _core.BUFFER_FORMAT_RGB_32
